# Generated by Django 3.0 on 2020-07-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='cart_id',
            new_name='card_id',
        ),
    ]
